USE [1]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TaskTypes](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar] (max) NULL,
CONSTRAINT [PK_TaskTypes] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tasks](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar] (256) NULL,
	[OpportunityID] [int] NOT NULL,
	[DueDate] [datetime] NOT NULL,
	[TypeID] [int] NOT NULL,
	[StatusID] [int]  NULL,
CONSTRAINT [PK_Tasks] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Opportunities](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Amount] [money] NOT NULL,
	[UserID] [nvarchar] (450) NOT NULL,
	[ContactID] [int] NOT NULL,
	[StatusID] [int] NOT NULL,
	[CloseDate] [datetime] NOT NULL,
	[Name] [nvarchar] (256) NOT NULL,
CONSTRAINT [PK_Opportunities] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OpportunityStatuses](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar] (max) NULL,
CONSTRAINT [PK_OpportunityStatuses] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TaskStatuses](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar] (256) NULL,
CONSTRAINT [PK_TaskStatuses] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Contacts](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Email] [nvarchar] (256) NOT NULL,
	[Company] [nvarchar] (256) NULL,
	[LastName] [nvarchar] (256) NULL,
	[FirstName] [nvarchar] (256) NULL,
	[Phone] [nvarchar] (256) NULL,
CONSTRAINT [PK_Contacts] PRIMARY KEY CLUSTERED
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[Tasks] WITH CHECK ADD CONSTRAINT [FK_Tasks_TypeID] FOREIGN KEY([TypeID])
REFERENCES [dbo].[TaskTypes] ([ID])
GO
ALTER TABLE [dbo].[Tasks] CHECK CONSTRAINT [FK_Tasks_TypeID]
GO
ALTER TABLE [dbo].[Tasks] WITH CHECK ADD CONSTRAINT [FK_Tasks_StatusID] FOREIGN KEY([StatusID])
REFERENCES [dbo].[TaskStatuses] ([ID])
GO
ALTER TABLE [dbo].[Tasks] CHECK CONSTRAINT [FK_Tasks_TypeID]
GO
ALTER TABLE [dbo].[Tasks] WITH CHECK ADD CONSTRAINT [FK_Tasks_OpportunityID] FOREIGN KEY([OpportunityID])
REFERENCES [dbo].[Opportunities] ([ID])
GO
ALTER TABLE [dbo].[Tasks] CHECK CONSTRAINT [FK_Tasks_OpportunityID]
GO
ALTER TABLE [dbo].[Opportunities] WITH CHECK ADD CONSTRAINT [FK_Opportunities_StatusID] FOREIGN KEY([StatusID])
REFERENCES [dbo].[OpportunityStatuses] ([ID])
GO
ALTER TABLE [dbo].[Opportunities] CHECK CONSTRAINT [FK_Opportunities_StatusID]
GO
ALTER TABLE [dbo].[Opportunities] WITH CHECK ADD CONSTRAINT [FK_Opportunities_ContactID] FOREIGN KEY([ContactID])
REFERENCES [dbo].[Contacts] ([ID])
GO
ALTER TABLE [dbo].[Opportunities] CHECK CONSTRAINT [FK_Opportunities_ContactID]