USE [2]
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customer](
	[CID] [int] IDENTITY(1,1) NOT NULL,
	[CPassword] [nvarchar] (256) NULL,
	[CTitle] [nvarchar] (256) NULL,
	[CFname] [nvarchar] (256) NULL,
	[CLname] [nvarchar] (256) NULL, 
	[CIC] [nvarchar] (256) NULL,
	[CNationality] [nvarchar] (256) NULL,
	[CContact] [nvarchar] (256) NULL,
	[CEmail] [nvarchar] (256) NULL,
	[CBankAcc] [int] NULL,
	[CBank] [nvarchar] (256) NULL,
	[TypeNum] [int] NOT NULL,
CONSTRAINT [PK_TaskTypes] PRIMARY KEY CLUSTERED
(
	[CID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Type](
	[TypeNum] [int] IDENTITY(1,1) NOT NULL,
	[CType] [nvarchar] (256) NULL,
CONSTRAINT [PK_Type] PRIMARY KEY CLUSTERED
(
	[TypeNum] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Admin](
	[AdID] [int] IDENTITY(1,1) NOT NULL,
	[AdPasswd] [nvarchar] (256) NULL,
	[AdName] [nvarchar] (256) NULL,
	[AdContact] [nvarchar] (256) NULL,
	[AdEmail] [nvarchar] (256) NULL,
CONSTRAINT [PK_Admin] PRIMARY KEY CLUSTERED
(
	[AdID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Reservation](
	[RxNum] [int] IDENTITY(1,1) NOT NULL,
	[CIN] [int] NULL,
	[COUT] [int] NULL,
	[NON] [int] NULL,
	[Status] [nvarchar] (256) NULL,
	[CID] [int] NOT NULL,
	[AdID] [int] NOT NULL,
	[RmID] [int] NOT NULL,
CONSTRAINT [PK_Reservation] PRIMARY KEY CLUSTERED
(
	[RxNum] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Invoice](
	[INum] [int] IDENTITY(1,1) NOT NULL,
	[TotalFee] [money] NULL,
	[Description] [nvarchar] (256) NULL,
	[Date] [Date] NULL,
	[RxNum] [int] NOT NULL,
CONSTRAINT [PK_Invoice] PRIMARY KEY CLUSTERED
(
	[INum] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Room](
	[RmID] [int] IDENTITY(1,1) NOT NULL,
	[RmType] [nvarchar] (256) NULL,
	[RmBedding] [nvarchar] (256) NULL,
	[RmPrice] [money] NULL,
	[RmStatus] [nvarchar] (256) NULL,
CONSTRAINT [PK_Room] PRIMARY KEY CLUSTERED
(
	[RmID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Rating](
	[RatingID] [int] IDENTITY(1,1) NOT NULL,
	[Rating] [nvarchar] (256) NULL,
	[RmID] [int] NOT NULL,
CONSTRAINT [PK_Rating] PRIMARY KEY CLUSTERED
(
	[RatingID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[Customer] WITH CHECK ADD CONSTRAINT [FK_Customer_TypeNum] FOREIGN KEY ([TypeNum])
REFERENCES [dbo].[Type] ([TypeNum])
GO 
ALTER TABLE [dbo].[Customer] CHECK CONSTRAINT [FK_Customer_TypeNum]
GO
ALTER TABLE [dbo].[Reservation] WITH CHECK ADD CONSTRAINT [FK_Reservation_CID] FOREIGN KEY ([CID])
REFERENCES [dbo].[Customer] ([CID])
GO
ALTER TABLE [dbo].[Reservation] CHECK CONSTRAINT [FK_Reservation_CID]
GO
ALTER TABLE [dbo].[Reservation] WITH CHECK ADD CONSTRAINT [FK_Reservation_AdID] FOREIGN KEY ([AdID])
REFERENCES [dbo].[Admin] ([AdID])
GO
ALTER TABLE [dbo].[Reservation] CHECK CONSTRAINT [FK_Reservation_AdID]
GO
ALTER TABLE [dbo].[Reservation] WITH CHECK ADD CONSTRAINT [FK_Reservation_RmID] FOREIGN KEY ([RmID])
REFERENCES [dbo].[Room] ([RmID])
GO
ALTER TABLE [dbo].[Reservation] CHECK CONSTRAINT [FK_Reservation_RmID]
GO
ALTER TABLE [dbo].[Invoice] WITH CHECK ADD CONSTRAINT [FK_Invoice_RxNum] FOREIGN KEY ([RxNum])
REFERENCES [dbo].[Reservation] ([RxNum])
GO
ALTER TABLE [dbo].[Invoice] CHECK CONSTRAINT [FK_Invoice_RxNum]
GO
ALTER TABLE [dbo].[Rating] WITH CHECK ADD CONSTRAINT [FK_Rating_RmID] FOREIGN KEY ([RmID])
REFERENCES [dbo].[Room] ([RmID])
GO
ALTER TABLE [dbo].[Rating] CHECK CONSTRAINT [FK_Rating_RmID]